apiVersion: v1
kind: Namespace
metadata:
  name: app-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-deploy
  namespace: app-test
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: app-test
  template:
    metadata:
      labels:
        app: app-test
    spec:
      containers:
      - name: app-test
        image: nginx
        ports:
        - name: web
          containerPort: 32222 
        readinessProbe:
          httpGet:
            path: /
            port: 32222
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 32222
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-test-svc
  namespace: app-test
  labels:
    app: app-test
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 32222  
    protocol: TCP
  selector:
    app: app-test
